spring:
  application:
    name: audit-trail-ws-msg-processor-drp-mx
  jmx:
    default-domain: audit-trail-ws-msg-processor-drp-mx
  profiles:
    active: lh

logging: 
  file: /u/users/atp/tmp/file_out/${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Properties
app:
  conf:
    maxTrailFieldLength: 3000
    scheduler:
      retryJob: "*/10 * * * * *"
    file:
      base-dir: "/u/users/atp/tmp/file_int"
      file-pattern: "([A-Z]{6})-audit-((?:(?:(?:(?:(?:[13579][26]|[2468][048])00)|(?:[0-9]{2}(?:(?:[13579][26])|(?:[2468][048]|0[48]))))(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:0[1-9]|1[0-9]|2[0-9]))))|(?:[0-9]{4}(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:[01][0-9]|2[0-8])))))(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9]){2}).log"
      prefix-file-pattern: "([A-Z]{6})"
      body-file-pattern: "-audit-"
      sufix-file-pattern: "((?:(?:(?:(?:(?:[13579][26]|[2468][048])00)|(?:[0-9]{2}(?:(?:[13579][26])|(?:[2468][048]|0[48]))))(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:0[1-9]|1[0-9]|2[0-9]))))|(?:[0-9]{4}(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:[01][0-9]|2[0-8])))))(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9]){2})"
      file-extension: ".log"
  topics:
    Security: security-audit-control-mx
    Business: 
    System: 

---
server:
  port: 6080

spring:
  profiles: lh

logging:
  file: /dev/logs/spring-boot/${spring.application.name}.log
  level:
    root: INFO
    com.darkarth.demo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG

# Custom Properties
app:
  conf:
    scheduler:
      retryJob: "*/10 * * * * *"
    file:
      base-dir: "/home/darkarth/dev/tests/files/audit-trails"
